# Generated by Django 3.2.3 on 2021-05-31 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked', models.BooleanField(default=False, help_text='Забронировать место на событии', verbose_name='Бронь места')),
                ('address', models.CharField(help_text='Укажите, место проведения события', max_length=200, verbose_name='Адрес')),
                ('contact', models.CharField(help_text='Укажите, контакт организатора события', max_length=200, verbose_name='Контакт')),
                ('title', models.CharField(help_text='Укажите, краткое описание предстоящего события', max_length=200, verbose_name='Название')),
                ('description', models.TextField(help_text='Укажите, полное описание предстоящего события', verbose_name='Описание')),
                ('start_at', models.DateTimeField(help_text='Укажите, дату и время начала события', verbose_name='Начало')),
                ('end_at', models.DateTimeField(help_text='Укажите, дату и время окончания события', verbose_name='Окончание')),
                ('seats', models.PositiveIntegerField(help_text='Укажите, количество посадочных мест', verbose_name='Кол-во мест')),
                ('city', models.ForeignKey(help_text='Укажите, наименование города проведения события', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='common.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ('city',),
            },
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(help_text='Выберите событие для пользователя', on_delete=django.db.models.deletion.CASCADE, related_name='event_follow', to='afisha.event', verbose_name='Событие')),
                ('user', models.ForeignKey(help_text='Выберите пользователя на предстоящее событие', on_delete=django.db.models.deletion.CASCADE, related_name='event_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
                'ordering': ('user',),
            },
        ),
        migrations.AddConstraint(
            model_name='eventparticipant',
            constraint=models.UniqueConstraint(fields=('user', 'event'), name='unique_participation'),
        ),
    ]
