# Generated by Django 3.2.3 on 2021-05-24 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_auto_20210524_1759'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('afisha', '0002_eventparticipant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('city',), 'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
        migrations.AlterModelOptions(
            name='eventparticipant',
            options={'ordering': ('user',), 'verbose_name': 'Участник', 'verbose_name_plural': 'Участники'},
        ),
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(help_text='Укажите, место проведения события', max_length=200, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.ForeignKey(help_text='Укажите, наименование города проведения события', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='common.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='event',
            name='contact',
            field=models.CharField(help_text='Укажите, контакт организатора события', max_length=200, verbose_name='Контакт'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(help_text='Укажите, полное описание предстоящего события', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_at',
            field=models.DateTimeField(help_text='Укажите, дату и время окончания события', verbose_name='Окончание'),
        ),
        migrations.AlterField(
            model_name='event',
            name='seats',
            field=models.IntegerField(help_text='Укажите, количество посадочных мест', verbose_name='Кол-во мест'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_at',
            field=models.DateTimeField(help_text='Укажите, дату и время начала события', verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='event',
            name='taken_seats',
            field=models.IntegerField(default=0, help_text='Укажите, количество занятых посадочных мест', verbose_name='Кол-во занятых мест'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(help_text='Укажите, краткое описание предстоящего события', max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='event',
            field=models.ForeignKey(help_text='Выберите событие для пользователя', on_delete=django.db.models.deletion.CASCADE, related_name='event_follow', to='afisha.event', verbose_name='Событие'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='user',
            field=models.ForeignKey(help_text='Выберите пользователя на предстоящее событие', on_delete=django.db.models.deletion.CASCADE, related_name='event_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
