# Generated by Django 3.2.3 on 2021-05-31 11:16

import bbbs.common.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название города', max_length=30, unique=True, validators=[bbbs.common.validators.city_name_validator], verbose_name='Имя')),
                ('is_primary', models.BooleanField(default=False, help_text='Укажите главный ли город', verbose_name='Главный')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ('-is_primary', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'администратор'), ('MODERATOR', 'модератор'), ('REGION_MODERATOR', 'региональный модератор'), ('MENTOR', 'наставник')], default='MENTOR', max_length=30, verbose_name='Роль')),
                ('city', models.ManyToManyField(help_text='Выберите один или несколько городов.<br>', related_name='profiles', to='common.City', verbose_name='Город')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили',
                'ordering': ('user__username',),
            },
        ),
    ]
