# Generated by Django 3.2.3 on 2021-05-23 12:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0004_alter_city_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Укажите основной ли город', verbose_name='Главный'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(help_text='Введите название города', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Название должно содержать только русские буквы.', regex='^[-а-яА-Я]+$')], verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='common.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
