# Generated by Django 3.2.3 on 2021-05-23 12:04

import bbbs.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20210523_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(help_text='Введите название города', max_length=30, unique=True, validators=[bbbs.common.validators.city_name_validator], verbose_name='Город'),
        ),
    ]
