# Generated by Django 3.2.3 on 2021-05-23 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_alter_city_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('is_primary', 'name'), 'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('user__username',), 'verbose_name': 'Профиль пользователя'},
        ),
    ]
