# Generated by Django 3.2.3 on 2021-05-23 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_auto_20210523_1211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('user',), 'verbose_name': 'Профиль пользователя'},
        ),
    ]
