# Generated by Django 3.2.3 on 2021-05-23 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_alter_profile_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('user__username',), 'verbose_name': 'Профиль пользователя'},
        ),
    ]
