# Generated by Django 3.2.3 on 2021-05-23 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_alter_profile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('-is_primary', 'name'), 'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
    ]
