# Generated by Django 3.2.3 on 2021-05-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_alter_city_is_primary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.ManyToManyField(blank=True, null=True, to='common.City', verbose_name='Город'),
        ),
    ]
