# Generated by Django 3.2.3 on 2021-05-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_auto_20210523_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.ManyToManyField(to='common.City', verbose_name='Город'),
        ),
    ]
